<header class="header">
    <div class="container header__container">
        <a href="/" class="header__title">TM</a>
        <div class="header__navbar">
            <div class="header__link">
                <a href="/profile">Профиль</a>
            </div>
            <div class="header__link">
                <a href="/tasks">Задачи</a>
            </div>
        </div>
        <div class="header__burger"><span></span></div>
    </div>
</header>